### ISSUE TITLE
RN 0.49.3 crashed on Android

### ISSUE THREAD

**Issue by jurajkrivda** [callstack/haul#251]
Hi.

I upgraded haul to 1.0.0-beta.6 due to breaking changes on iOS. Now, iOS is working fine, but Android will stop right after launching the app. When I change the version back to beta.5 everything works well on Android. On beta.6 I got messsage: `GET /index.android.bundle 500 undefined - 4.247 ms`

**Comment by Krizzu** [comment]
With RN 0.49 +, android should serve `index.bundle`.

Can provide your file structure?
Do You get any warnings on startup?

**Comment by satya164** [comment]
Maybe you need to recompile the app?

**Comment by jurajkrivda** [comment]
No. Any warnings. My file structure is the same as before.
I have `index.android.js` and `webpack.haul.js` in the root of the application. Here is my webpack config:

```
const path = require("path");

module.exports = ({ platform, root }, defaults) => ({
  entry: `./index.${platform}.js`,
  module: {
    ...defaults.module,
    rules: [
      ...defaults.module.rules,
      {
        test: /\.js$/,
        include: /lottie-react-native/,
        use: "babel-loader"
      }
    ]
  },
  resolve: {
    ...defaults.resolve,
    alias: {
      ...defaults.resolve.alias,
      styles: path.join(root, "src", "styles"),
      ui: path.join(root, "src", "components", "UI")
    }
  }
});
```

**Comment by jurajkrivda** [comment]
@satya164 I tried to recompile my app many times. Also I tried deleting node_modules and installed dependencies again.

**Comment by Krizzu** [comment]
Looks like your app tries to get bundle from `index.android.bundle`, while this path is valid for > RN 0.49.x.

Can you double check RN version You have (by checking RN's version in it's `package.json`).
And By `recompile` you mean `re-installing` app on your phone/emulator, right?

**Comment by jurajkrivda** [comment]
Yes, I removed the app from my device by `adb uninstall...` and then I run haul and run app again.

Here is my package.json. 

```
{
  "name": "App",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^8.0.1",
    "babel-jest": "^21.2.0",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-preset-react-native": "^4.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "eslint": "^4.8.0",
    "eslint-config-dacz": "^0.13.3",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "haul": "1.0.0-beta.6",
    "jest-expo": "^21.0.2",
    "prettier-eslint": "^8.2.0",
    "prop-types": "^15.6.0",
    "react-dom": "^16.0.0",
    "react-native-debugger-open": "0.3.15",
    "react-test-renderer": "16.0.0-beta.5",
    "reactotron-react-native": "^1.12.3"
  },
  "scripts": {
    "start": "react-native start",
    "android:dev": "cd android && ./gradlew installDebug",
    "android:prod": "react-native run-android --variant release",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "build:android": "haul bundle --platform android --entry-file index.android.js --bundle-output build/index.android.bundle --assets-dest build --dev false",
    "storybook": "storybook start -p 7007 --haul webpack.haul.storybook.js",
    "haul": "haul start"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-cache-inmemory": "0.2.0-rc.0",
    "apollo-client": "2.0.0-beta.4",
    "apollo-client-preset": "^0.1.0-1",
    "apollo-link": "0.7.0",
    "apollo-link-http": "0.6.1-beta.6",
    "apollo-link-set-context": "^0.6.1-beta.1",
    "graphql": "^0.11.4",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^2.2.1",
    "lottie-react-native": "2.2.7",
    "moment": "2.19.1",
    "ramda": "0.25.0",
    "react": "16.0.0-beta.5",
    "react-apollo": "^1.4.16",
    "react-native": "0.49.3",
    "react-native-android-statusbar": "^0.1.3",
    "react-native-calendars": "^1.7.1",
    "react-native-code-push": "5.1.3-beta",
    "react-native-config": "0.8.1",
    "react-native-elements": "^0.17.0",
    "react-native-i18n": "2.0.7",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-splash-screen": "^3.0.1",
    "react-native-vector-icons": "4.4.2",
    "react-navigation": "^1.0.0-beta.13",
    "react-redux": "^5.0.6",
    "recompose": "0.26.0",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by jurajkrivda** [comment]
Looked at package.json in RN package:

```
 ...
  "name": "react-native",
  "version": "0.49.3",
...
```

**Comment by Krizzu** [comment]
As temp. solution, You can add this to your `webpack.haul.config`
```js
output: {
        ...output,
        filename: `index.${platform}.bundle`,
    },
```

**Comment by jurajkrivda** [comment]
Thanks. I can confirm it works!

**Comment by MasahiroMorita** [comment]
With RN0.49+, haul should serve the same `index.bundle` but `index.bundle?platform=android` for Android, and `index.bundle?platform=ios` for iOS. However, the current implementation of haul seems to ignore `platform=` parameter. 

do you have any plans to support this feature?

In my case, I modified `ios/appname/AppDelegate.m`:
```
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
```
`@"index"` to `@"index.ios"`,  and added this to `webpack.haul.config`:
```
  output: {
    ...defaults.output,
    filename: `index${platform == 'ios' ? '.ios' : ''}.bundle`,
  },
```

By modifying this, Android app will retrieve `/index.bundle` and iOS app retrieve `/index.ios.bundle` separately.

Is there any solutions?

**Comment by Krizzu** [comment]
Hey @MasahiroMorita, I'll try to land PR this week. Thanks for bringing this up.

**Comment by MasahiroMorita** [comment]
Actually, I gave up migrating RN0.49, used RN 0.48 instead at this moment...
In addition to my last comment, I faced many incompatibility problems. I couldn't resolve them. You should test RN0.49 problems very carefully.

**Comment by Krizzu** [comment]
Could You elaborate bit more about those incompatibility problems? That would help us out tracking it down.
Thanks

**Comment by MasahiroMorita** [comment]
Yes, the largest one is caused on a real device.
On emulators, iOS and Android app work fine, but do not on real devices.
It looks that the app can't find bundled JS files from their assets.

And the other one is the integration of code push.
I couldn't find how to integrate haul on RN0.49 with code-push.

I hope haul should be merged a part of official react-native.
Your work is great. more people should use this.

**Comment by Krizzu** [comment]
Great, thanks for hints! We'll look into this issue.

About CP - [have You checked docs about integrating haul with codepush](https://github.com/callstack/haul/blob/master/docs/Code%20Push.md) ?

**Comment by Krizzu** [comment]
Hopefully fixed in #276

**Comment by gsteyn** [comment]
@Krizzu, I vote for reopening this issue, as #276 didn't seem to fix it.
I tried using `1.0.0-beta.9`, which has the commit to fix this issue, with RN `0.49.5` and my app still crashes on Android. The packager still tries to serve `index.android.bundle` instead of `index.bundle`.

**Comment by Krizzu** [comment]
hey @gsteyn 
#276 has added an middleware that will change request for `index.bundle` to `index.android.bundle`. This should not affect anything with devices.

I'll try to repro it on fresh app

**Comment by grabbou** [comment]
Unfortunately, we couldn't reproduce it. Is it possible you provide us with a `zip` file to reproduce the issue? Does anyone else is still having this problem?

**Comment by thymikee** [comment]
Closing due to inactivity. Happy to reopen if you have more info on that :)

**Comment by MaheshNandam** [comment]
I have deleted this line from build.gradle file, its working fine now,

compile 'com.airbnb.android:lottie:2.5.0-rc1'
